### ISSUE TITLE
Internal lv: Trrricksters!! MASTER is 14.5

### ISSUE THREAD

**Issue by euph00** [myjian/mai-tools#43]
![E829BD41-297E-4901-8F13-848B3821297E](https://user-images.githubusercontent.com/88617351/222734692-c352a110-aaac-43c8-9a56-2d8e87b0a4bc.png)
SSS+ gives 326 rating (660 —> 986)

**Comment by myjian** [comment]
Thank you. Updated in d36c5de164cb874d9680ae17dd7dfbac77c53936
