### ISSUE TITLE
Feature request: more details in download all scores (tsv form)

### ISSUE THREAD

**Issue by DadangSudadang** [myjian/mai-tools#46]
### Expected behavior
Print column headers and more fields in tsv format.

| Title | Genre | Version | Difficulty | Lv. | CC | Chart | Achievement | Rank | DX Score | DX% | DX* |  FC/AP | Sync | Last Played | No. of Play(s) |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |
| うまぴょい伝説 | POPS＆アニメ | UNiVERSE PLUS | Re:MASTER | 13 | 13.5 | DX | 96.2822% | AAA | 2117/2490 | 85.0% | 1 | - | - | 2023/04/25 23:39 | 1 |

```
Title	Genre	Version	Difficulty	Lv.	CC	Chart	Achievement	Rank	DX Score	DX%	DX*	FC/AP	Sync	Last Played	No. of Play(s)
うまぴょい伝説	POPS＆アニメ	UNiVERSE PLUS	Re:MASTER	13	13.5	DX	96.2822%	AAA	2117/2490	85.0%	1	-	-	2023/04/25 23:39	1
```

### Additional requirements/caveats:
- Show *, ? or - if the internal level is unknown
- Show FC/FC+/AP/AP+ or - if none
- Show FS/FS+/FDX/FDX+ or - if none
- If percentage does not reach at least 1 star, show DX* as -

### Options
1. Add the features to the current implementation, but that would mean also modifying the intrepreters for the analyzer
2. Add as a separate function, maybe a checkbox "include more details" or a different button under the textbox
    ![image](https://user-images.githubusercontent.com/74943749/234476301-c999f8b5-c24e-49ac-a58e-af3b4afb385b.png)
3. If there are too many unnecessary fields, maybe just keep dxscore, fc/ap/sync status, timestamp and no. of plays?

**Comment by myjian** [comment]
Last Played and No. of Play(s) cannot be batch retrieved, as they are only visible on per-song score page.
Version requires a lookup table from [song name + chart type] -> [version], but is doable.

~~May I ask what CC stands for?~~
never mind, it is chart constant.

**Comment by myjian** [comment]
never mind, it is chart constant.

**Comment by DadangSudadang** [comment]
Thank you very much!
