### ISSUE TITLE
Refactor: Deploy github pages with actions

### ISSUE THREAD

**Issue by Luxusio** [myjian/mai-tools#60]
Current developing environment is not comfortable.
Source code contains its build result. Which causes conflict. 
It is hard to contribute many people at once.
I think it should be improved quickly.

So I decided to contribute Deploy github pages with actions.
I made a sample project about [deploying github pages via github actions](https://github.com/Luxusio/gh-pages-deploy-pages-action-sample).

This is my following plan.

1. Use CSS Bundler to bundle css
2. Use copy plugin to copy html & data
3. Set build output directory to 'build' and remove all unnecessary folders
4. Build&Deploy github page via Github Actions

Repository's owner should change github page deploy option to 'action' to achive this goal.
Can you help me, @myjian?

**Comment by Luxusio** [comment]
I'm currently working on my [forked repository](https://github.com/Luxusio/mai-tools/tree/feature/deploy-pages-via-action)

**Comment by Luxusio** [comment]
I successfully deployed artifact via github actions, but analyze rating is not working yet

https://luxusio.github.io/mai-tools/

**Comment by myjian** [comment]
Try adding `https://luxusio.github.io/` to ALLOWED_ORIGINS in src/common/util.ts. This should make analyze rating work.

**Comment by myjian** [comment]
Thank you for working on this.

I would prefer having all files that are copied by CopyPlugin in the static folder, which would make the folder structure and webpack configuration look like this:
![image](https://github.com/myjian/mai-tools/assets/1978764/9724045c-e332-432b-88cb-324ac7867f79)
