### ISSUE TITLE
Bug: Calculate score shows break as touch

### ISSUE THREAD

**Issue by Luxusio** [myjian/mai-tools#78]
as content

![image](https://github.com/myjian/mai-tools/assets/44326048/b4064d88-8989-4bc5-950f-5a159b4d544c)

![image](https://github.com/myjian/mai-tools/assets/44326048/c62b85dc-32dd-4297-bd24-c1b6b7d4d389)

**Comment by myjian** [comment]
can you share the URL of the analysis result page?

**Comment by Luxusio** [comment]
error does not reproduced in desktop chrome.
I experienced this error in ipad safari

https://myjian.github.io/mai-tools/classic-layout/?dt=1694884260000&tk=TRACK+3&st=%E9%AD%94%E6%B3%95%E5%B0%91%E5%A5%B3%E3%81%AB%E3%81%AA%E3%82%8B%E3%81%97%E3%81%8B%E3%81%AD%E3%81%87&df=3&ac=99.1677&hs=1&nd=11-14-5-3-0_122-0-2-0-0__53-25-9-0-0_&cb=943%2F956
