### ISSUE TITLE
FiNALE achievement -> DX achievement calculation error

### ISSUE THREAD

**Issue by myjian** [myjian/mai-tools#8]
These are valid FiNALE scores but they don't convert to DX achievements.
https://myjian.github.io/mai-tools/dx-achievement/?achv=99.13&bs=13000&ts=342000&bj=526-35-0-0
https://myjian.github.io/mai-tools/dx-achievement/?achv=99.51&bs=12950&ts=401550&bj=586-13-2-1

**Comment by Tomfbyyy** [comment]
你的maimai 書籤小工具合集 (MMBL)壞了 每首歌曲的數值不準確了

**Comment by myjian** [comment]
> 你的maimai 書籤小工具合集 (MMBL)壞了 每首歌曲的數值不準確了

這個 Issue 與你敘述的問題無關，下次請開新的 Issue。
Your comment is not related to this issue. Please create a new issue next time.

**Comment by myjian** [comment]
There were wrong numbers in break judgements.

The first one should be:
https://myjian.github.io/mai-tools/dx-achievement/?achv=99.13&bs=13000&ts=342000&bj=5-0-0-0

The second one should be:
https://myjian.github.io/mai-tools/dx-achievement/?achv=99.51&bs=12950&ts=401550&bj=5-0-0-0

* * * *

Appendix
====

Song 1 - ガラテアの螺旋 99.13％ / 99.9855%
----

```
Total	526	35	0	0	342,000

Tap	458	35	0	0	243,000
Hold	17	0	0	0	17,000
Slide	46	0	0	0	69,000
Break	5	0	0	0	13,000
```

Song 2 - Destr0yer [DX] 99.51％ / 100.3552%
----

```
Total	586	13	2	1	401,550

Tap	350	12	2	0	180,300
Hold	52	1	0	0	52,800
Slide	66	0	0	0	99,000
Touch	113	0	0	1	56,500
Break	5	0	0	0	12,950
```
